export const EXPERTISE_TAGS = [
  "Chartered Accountancy",
  "Audit — Statutory & Internal",
  "Direct & International Tax",
  "GST & Indirect Tax",
  "MSME Finance & Credit",
  "CFO Services",
  "M&A / Investment Banking",
  "Private Equity & Fundraising",
  "Valuation & Due Diligence",
  "Wealth Management",
  "Structured & Cross-border Finance",
  "IPO Advisory",
  "Advocate / Litigation",
  "Corporate & Commercial Law",
  "Property & Succession",
  "Company Secretary",
  "Data Privacy / DPDP",
  "ISO & Certifications",
  "Strategy & Corporate Development",
  "Management Consulting",
  "HR & Organisation Design",
  "Recruitment & Staffing",
  "Sales & Marketing (B2B)",
  "Brand & Digital Marketing",
  "Training & Skill Development",
  "Business Analysis & ERP",
  "AI & Automation",
  "SaaS & Product",
  "Software Engineering",
  "Cybersecurity",
  "Real Estate — Industrial & Pre-leased",
  "Real Estate — Redevelopment",
  "Asset Sales & Business Transfers",
  "Healthcare & Hospitals",
  "Pharma",
  "Auto Components",
  "Manufacturing & Engineering",
  "Retail",
  "EPC & Infrastructure",
  "Logistics & Warehousing",
  "Banking & NBFC",
] as const;
